version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    day: "friday"
    time: "16:30"
    timezone: "Europe/Prague"
  labels: 
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
  groups:
    kotlin:
      patterns:
        - "jetbrains.kotlin.*"
    android-x:
      patterns:
        - "androidx.*"

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: "friday"
    time: "16:30"
    timezone: "Europe/Prague"
  labels: 
    - 'dependencies'
  open-pull-requests-limit: 3
  assignees:
    - "yasanglass"
