[versions]
agp = "8.12.3"
android-sdk-compile = "36"
android-sdk-min = "23"
android-sdk-target = "36"
androidx-activity-compose = "1.12.2"
androidx-browser = "1.9.0"
androidx-compose-ui-tooling = "1.10.1"
androidx-lifecycle = "2.9.6"
androidx-navigation = "2.9.1"
arturbosch-detekt = "1.23.8"
codingfeline-buildkonfig = "0.17.1"
glass-yasan-kepko = "1.2.13"
glass-yasan-toolkit = "1.7.4"
iurysouza-modulegraph = "0.13.0"
jetbrains-compose = "1.9.3"
jetbrains-compose-hotreload = "1.0.0"
jetbrains-kotlin = "2.3.0"
jetbrains-kotlinx-collections-immutable = "0.4.0"
jetbrains-kotlinx-coroutines = "1.10.2"
jetbrains-kotlinx-kover = "0.9.4"
jetbrains-kotlinx-serialization = "1.9.0"
junit = "4.13.2"
koin = "4.1.1"
roborazzi = "1.56.0"
russhwolf-multiplatform-settings = "1.3.0"
sergio-sastre-composable-preview-scanner = "0.8.1"
sqldelight = "2.2.1"
touchlab-kermit = "2.0.8"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui-tooling" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
glass-yasan-kepko-component = { module = "glass.yasan.kepko:component", version.ref = "glass-yasan-kepko" }
glass-yasan-kepko-foundation = { module = "glass.yasan.kepko:foundation", version.ref = "glass-yasan-kepko" }
glass-yasan-toolkit-about = { module = "glass.yasan.toolkit:about", version.ref = "glass-yasan-toolkit" }
glass-yasan-toolkit-compose = { module = "glass.yasan.toolkit:compose", version.ref = "glass-yasan-toolkit" }
glass-yasan-toolkit-core = { module = "glass.yasan.toolkit:core", version.ref = "glass-yasan-toolkit" }
glass-yasan-toolkit-koin = { module = "glass.yasan.toolkit:koin", version.ref = "glass-yasan-toolkit" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "jetbrains-kotlinx-collections-immutable" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "jetbrains-kotlinx-serialization" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
roborazzi-compose-desktop = { module = "io.github.takahirom.roborazzi:roborazzi-compose-desktop", version.ref = "roborazzi" }
russhwolf-multiplatform-settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "russhwolf-multiplatform-settings" }
russhwolf-multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "russhwolf-multiplatform-settings" }
russhwolf-multiplatform-settings-make-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "russhwolf-multiplatform-settings" }
sergio-sastre-composable-preview-scanner-jvm = { module = "io.github.sergio-sastre.ComposablePreviewScanner:jvm", version.ref = "sergio-sastre-composable-preview-scanner" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-sqlite-driver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "touchlab-kermit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
arturbosch-detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "arturbosch-detekt" }
codingfeline-buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "codingfeline-buildkonfig" }
iurysouza-modulegraph = { id = "dev.iurysouza.modulegraph", version.ref = "iurysouza-modulegraph" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-compose-hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "jetbrains-compose-hotreload" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "jetbrains-kotlinx-kover" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
